### ISSUE TITLE
Set EntityReference attribute to NULL

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#112]
The following code is not working:

````
Update-CrmRecord -EntityLogicalName "account" -Id $testid -Fields @{ "territoryid" = $null  }
````

This will given an error:
````
Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In C:\Users\drt\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:699 Zeichen:12
+            $newfield = New-Object -TypeName 'Microsoft.Xrm.Tooling.Co ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
In C:\Users\drt\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:762 Zeichen:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
````
Is there an option to set the value for an enity-reference to NULL?

**Comment by kenakamu** [comment]
This is a bug. Current workaround is get the account record and set territory id to null.
```powershell
$account = Get-CrmRecord -EntityLogicalName "account" -Id $testid -Fields territoryid
$account.territoryid = $null
Set-CrmRecord $account
```

I will fix the bug when you specify fields directly later.

**Comment by kenakamu** [comment]
Fixed

**Comment by mattp65** [comment]
The fix that is checked in does not fix this.  The following switch needs to be wrapped in an "else" block for the provided IF check.

**Comment by kenakamu** [comment]
I will check it again.

**Comment by mattp65** [comment]
Sorry, I should have provided more context than I did.

Checked in "fix" is the following:
```
$newfield = New-Object -TypeName 'Microsoft.Xrm.Tooling.Connector.CrmDataTypeWrapper'
if($field.Value -eq $null)  
{  
	$newfield.Type = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::Raw  
}  

switch($field.Value.GetType().Name)
{
   ...
}


```

The logic in the switch wipes out the null value set.  This just needs to be changed to the following:

```
$newfield = New-Object -TypeName 'Microsoft.Xrm.Tooling.Connector.CrmDataTypeWrapper'
if($field.Value -eq $null)  
{  
	$newfield.Type = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::Raw  
}  
else {
	switch($field.Value.GetType().Name)
	{
		...
	}
}
```

Matt

**Comment by kenakamu** [comment]
Great. fixed!
