### ISSUE TITLE
How to set an datetime attribute to null?

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#79]
This code will generate an error, "foobar_stagecompletedon" is an date-time attribute.
````
Set-CrmRecord -EntityLogicalName 'foobar_salesstagesstatistic' `
     -conn $conn `
     -Id $item.ap_salesstagesstatisticid `
     -Fields @{ 
         foobar_stagecompletedon = $null 
       }
````

Error:
````
Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In C:\Users\drt\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:1059 Zeichen:12
+            $newfield = New-Object -TypeName 'Microsoft.Xrm.Tooling.Co ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

````

**Comment by thuld** [comment]
Using `[Nullable[DateTime]]$null` instead of `$null` does not the trick...

**Comment by seanmcne** [comment]
Yuck, I can see why that wouldn't be ideal.  Ken and I were recently talking about the method in which we're doing updates - we should be able to see if there's a better way to do this.  I'm thinking accepting $Null for a date/time should be an acceptable assumption :)

**Comment by kenakamu** [comment]
fixed.

**Comment by lankster** [comment]
This is only fixed when using the CrmRecord parameter syntax `Set-CrmRecord -Conn $conn -CrmRecord $record`, not when using the syntax the OP used in his question. That syntax still throws an error:

> [ERROR] MapFieldTypeByFieldValue : Cannot bind argument to parameter 'Value' because it is null.
[ERROR] At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:735 char:62
[ERROR] + ...         $newfield.Type = MapFieldTypeByFieldValue -Value $field.Value
[ERROR] +                                                              ~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : InvalidData: (:) [MapFieldTypeByFieldValue], ParameterBindingValidationException
[ERROR]     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,MapFieldTypeByFieldValue

And after looking through  `Microsoft.Xrm.Data.Powershell.psm1` I found that this code is hit when the `CrmRecord` parameter is null.
