### ISSUE TITLE
Can't create salesorderdetail using New-CrmRecord

### ISSUE THREAD

**Issue by bijns** [seanmcne/Microsoft.Xrm.Data.PowerShell#96]
Can't find a way to add a salesorderId reference. Always returns an empty Guid.

**Comment by seanmcne** [comment]
Can you share the command you ran, for context?

**Comment by bijns** [comment]
$salesorderdetailId = New-CrmRecord -conn $CRMConn -EntityLogicalName salesorderdetail @{ 
"quantity"="1";
"salesorderid"=$salesorderReference;
"productid"=$productReference;
"uomid"=$uomidReference}

**Comment by kenakamu** [comment]
Please use 1D as quantity like "quantity"=1D, which makes sure this is decimal value.
The reason why it doenst show error but return Empty Guid is a bug which fixed in the latest module. We will release it as v2.3 later.

**Comment by bijns** [comment]
Thanks, but I'm still unable to create anything like salesorderdetail or contractdetail or invoicedetail. Every 'detail' entity results in an empty Guid. Maybe the reference to salesorder, contract, invoice is wrong?

$contractId = New-CrmRecord -conn $CRMConn -EntityLogicalName contract @{
	"customerid"=New-CrmEntityReference -EntityLogicalName contact -Id $contactId;
	"title"="tst25";
	"activeon"=[datetime]"2016-03-26";
	"expireson"=[datetime]"2016-04-30"
	"billingcustomerid"=New-CrmEntityReference -EntityLogicalName contact -Id $contactId;
	"contracttemplateid"=$contracttemplateReference}

$contractdetailId = New-CrmRecord -conn $CRMConn -EntityLogicalName contractdetail @{
	"contractid"=New-CrmEntityReference -EntityLogicalName contract -Id $contractId;
	"title"="tst25"}

**Comment by kenakamu** [comment]
You can check the error by displaying $conn. Please let me know the error detail.

**Comment by kenakamu** [comment]
It's interesting as I could create salesorder item by using your original code. (I didn't specify isproductoverridden/ispriceoverriden though) 
Did you create productid and uomid as EntityReference like you did for salesorderid? Please make sure uom you selected is valid for the product.

**Comment by kenakamu** [comment]
as no update, closing it for now, but please re-open if you still have the issue
